// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class mti_test_2
{
        public const string achievement_test_ach4 = "CgkIt-C-yfoGEAIQBA"; // <GPGSID>
        public const string achievement_test_ach5 = "CgkIt-C-yfoGEAIQBQ"; // <GPGSID>
        public const string achievement_test_ach1 = "CgkIt-C-yfoGEAIQAQ"; // <GPGSID>
        public const string achievement_test_ach2 = "CgkIt-C-yfoGEAIQAg"; // <GPGSID>
        public const string achievement_test_ach3 = "CgkIt-C-yfoGEAIQAw"; // <GPGSID>

}

